language: rust
cache: cargo
sudo: required
os:
- linux
- osx
rust:
- stable
services:
- docker
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
matrix:
  include:
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
before_script:
- |
  (cargo install rustfmt || true) &&
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$HOME/.cargo/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  cargo fmt -- --write-mode=diff &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo --only nightly doc-upload
- travis-cargo --only nightly --no-sudo coveralls
before_deploy: "./build-release conductor ${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
env:
  global:
    secure: tal0xa4ro9Qd50osPTRELV46VMj3h0kdCFdgxMPoQt2PTYBOPYxRUP8XvgzVcg6PPEkSvtwsrCNDPNNQVctmCIC9QKtFiuznGRPVEz9Da5KfFweddJTCH8Mz9F57EPigA0vdNSLmu+N1pJaDl9AQYXO9cpAiHA4p9sPr7fnQsp6cn5byngJJJYN95Owfs7ahjJrigQYfikq+beqFQnngQBBq6CL0GQkYHp+dv2Z2mrS3+Wm+rnQtlDwdfoCyXAd+u5czMwOiMZNUqffZPpo5new4dmvaXlgMygsZtsKjzTZEJnuA3Kp0DfAA275crkfM7Su2j04RV7W9svwbqxZcqp6kAwOc5lpijrk/DM3KlJOZ/Bwa7CK8+oHmhFXZJvIOiczfkTtCOt0JOIotwoWlzvLFg0YhVzGdcwfwSpNL7cDCZpwsiHyMvZuxaX5ZaCbyLKAKONnBlaNFyumo4Vcah2LE8TU+QUW7dkx75oUfDeBt/NGbgniTwsc2cIkNWl340aCPxTjBU7yO7wofqHLpRrIyJzsC5Vy0tgAA6aDwKFH49OtXorUrqpG+BF2nb+APXvXvIEwXPpNhfpZjMADXxWjfMAmemniR5CQjJl+o0QJURoKUjNvxS6VQW4I5FrTJERPgRowkhLMC9ejYLgaQX4FCMbQZq34he3dIF4ansao=
deploy:
  provider: releases
  api_key:
    secure: XxzjVK+KvEew2d/uCQ78i9Wx5OII/Nb6eVKND5oIItYq3HiZeNee7fen1p7fB1/TTsw/MhWm29aCmEZNJ+bihwJbeQDgTPuWWYPx785ryF5AxaZmHeLWs9uPotJbukOuiNL+xkcOQ8RZOZvCs5elJ9LW36MftbZBRsR6F1MY19b6nq57SCptKy1DTvhoJ3VyOQ/Xu7hSIQkpDPWaFVIHfkaaeOJN3Cc0QjEsWhMuA4gv+8WSvzvci5/xTSqbux7+UPau12yANVhFHkTHfpFjjPT27Hziiq86FPdWmi+YZXlNqVtDvyYtCQ2cAXj0rdfSBXWVfoRxwEptu/EF0mzFERSifZvoqQEAHGmQ2mAoUPO3B7FubMi8ni7uURcgEG1S+5+51Jz/5BM78bPTywznIH1IHgG6ABCSzrdW7t5AD7nvgQa96ePXg4nb9+iYC6Z+5mtffEmg29wJy0ictMVFc/fokSPBNiZA+6SjUfXEIcwGdD+EwOMmWod/IFe6E4vQci1JHH2uZfH4gYbivCIYyaJ6wVkqCTRP+b9wDyMO4jvlDof8mOewa/F2QoqlkRM2Q1N0nKpfrtJE0LpDV1cft4BGj72NCzhafneHI2jI70liKUUX/XmNEvG2hqvFRXHupnExy2gvVHzngGEMGtlkHJ1FEFE8SQed5BEBuWJMSVQ=
  file_glob: true
  file: "conductor-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: faradayio/conductor
    rust: stable
    tags: true
