language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
os:
- linux
- osx
rust:
- stable
matrix:
  include:
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:PATH=$HOME/Library/Python/2.7/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo --only nightly doc-upload
- travis-cargo --only nightly --no-sudo coveralls
env:
  global:
    secure: tal0xa4ro9Qd50osPTRELV46VMj3h0kdCFdgxMPoQt2PTYBOPYxRUP8XvgzVcg6PPEkSvtwsrCNDPNNQVctmCIC9QKtFiuznGRPVEz9Da5KfFweddJTCH8Mz9F57EPigA0vdNSLmu+N1pJaDl9AQYXO9cpAiHA4p9sPr7fnQsp6cn5byngJJJYN95Owfs7ahjJrigQYfikq+beqFQnngQBBq6CL0GQkYHp+dv2Z2mrS3+Wm+rnQtlDwdfoCyXAd+u5czMwOiMZNUqffZPpo5new4dmvaXlgMygsZtsKjzTZEJnuA3Kp0DfAA275crkfM7Su2j04RV7W9svwbqxZcqp6kAwOc5lpijrk/DM3KlJOZ/Bwa7CK8+oHmhFXZJvIOiczfkTtCOt0JOIotwoWlzvLFg0YhVzGdcwfwSpNL7cDCZpwsiHyMvZuxaX5ZaCbyLKAKONnBlaNFyumo4Vcah2LE8TU+QUW7dkx75oUfDeBt/NGbgniTwsc2cIkNWl340aCPxTjBU7yO7wofqHLpRrIyJzsC5Vy0tgAA6aDwKFH49OtXorUrqpG+BF2nb+APXvXvIEwXPpNhfpZjMADXxWjfMAmemniR5CQjJl+o0QJURoKUjNvxS6VQW4I5FrTJERPgRowkhLMC9ejYLgaQX4FCMbQZq34he3dIF4ansao=
