[package]
name = "cage"
version = "0.0.20"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Develop multi-pod docker-compose apps"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faradayio/cage"
documentation = "https://faradayio.github.io/cage/"

build = "build.rs"

[features]
default = ["serde_codegen", "compose_yml/default"]
unstable = ["serde_derive", "compose_yml/unstable", "clippy"]

[[bin]]
name = "cage"
doc = false
test = true

[build-dependencies]
glob = "0.2.11"
includedir_codegen = "0.2.1"
serde_codegen = { version = "0.8", optional = true }

[dependencies]
clippy = { version = "0.0.*", optional = true }
compose_yml = { version = "0.0.42", default-features = false }
docopt = "0.6.83"
env_logger = "0.3.4"
error-chain = "0.5.0"
glob = "0.2.11"
handlebars = "0.21.0"
hashicorp_vault = "0.6.1"
includedir = "0.2.1"
lazy_static = "0.2.1"
log = "0.3.6"
phf = "0.7.16"
rand = "0.3.14"
retry = "0.4.0"
rustc-serialize = "0.3.19"
semver = "0.4.1"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_yaml = "0.4.0"
shlex = "0.1.1"
url = "1.2.0"
