[package]
name = "conductor"
version = "0.0.6"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Faraday Conductor: Develop and orchestrate multi-pod docker-compose apps"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faradayio/conductor"
documentation = "https://faradayio.github.io/conductor/"

build = "build.rs"

[features]
# This is just here to keep travis-cargo happy; we don't do anything special
# for nightly Rust.
unstable = []

[[bin]]
name = "conductor"
doc = false

[build-dependencies]
glob = "0.2.11"
includedir_codegen = "0.2.1"

[dependencies]
docker_compose = "0.3.5"
docopt = "0.6.83"
env_logger = "0.3.4"
glob = "0.2.11"
handlebars = "0.20.5"
includedir = "0.2.1"
lazy_static = "0.2.1"
log = "0.3.6"
phf = "0.7.16"
rand = "0.3.14"
regex = "0.1.73"
retry = "0.4.0"
rustc-serialize = "0.3.19"
shlex = "0.1.1"
